### PR TITLE
Sigil support

### PR DESCRIPTION
**Pull request by pfraze**
Update to use link sigils.

Still figuring out how deep the changes need to be here. Currently, this PR affects key-generation by prepending an `@` to the `id` of a key object, and leaving `public` and `private` alone.

### CODE REVIEW

**Comment by dominictarr** [comment]
:+1:

**Comment by dominictarr** [comment]
it might be an idea to put `@` at the start of the public key, and something else at the start of the private key.
actually `#` would be good because it acts as a comment in bash, and isn't sent to the server in a url
so you are kinda protected from copypasting your private key

**Comment by dominictarr** [comment]
merged into 4.0.0

**Comment by pfraze** [comment]
I had a similar thought. # seems good to me

**Pull request merged**
