### PR TITLE
browserify transforms +++

### PR DESCRIPTION
**Pull request by dangerousbeans**

### CODE REVIEW

**Comment by dominictarr** [comment]
can you link me to a script to reproduce this problem? because I am able to browserify this as it is... seems like there might be another problem?

**Comment by dangerousbeans** [comment]
I was seeing it when browserifying from patchcore, cuz I think by default browserify doesn't swap modules inside node_modules unless you hit it with the -g flag for a transform instead of the -t

Here's the fork of patchcore: https://github.com/dangerousbeans/patchcore/tree/browserify

Run
```
browserify -g [ browserify-replace --replace '{ "from": "^(#.+)", "to": "" }' ] -g aliasify example/index.js | indexhtmlify > index.html
```

Right now it actually seems to pack! But I'm trying to piece it together so the different way of injecting the keys still lets patchcore have...entry or whatever

**Comment by dangerousbeans** [comment]
:no_idea_what_im_doing_dog:

**Comment by dominictarr** [comment]
why do you need all that weird stuff in browserify, in particular what does: `browserify-replace --replace '{ "from": "^(#.+)", "to": "" }'` do?

**Comment by dominictarr** [comment]
why do you need all that weird stuff in browserify, in particular what does: `browserify-replace --replace '{ "from": "^(#.+)", "to": "" }'` do?

**Comment by dangerousbeans** [comment]
the replace thing strips out the `#!/bin/bash` lines so that the rest of it doesn't freak out

aliasify is switching `net` with `net-browserify-ws`

**Comment by dominictarr** [comment]
you can just use `browserify --unshebang` and it ignores `#!` (once upon a time this was on be default... but [whatever](https://github.com/browserify/browserify#bpipeline))

you also shouldn't need to replace net - if ssb-client is given a ws multiserver address as the remote it will use websockets instead. [like this](https://github.com/dominictarr/patchless/blob/master/modules/sbot.js#L92)

**Pull request closed without merging**
