### PR TITLE
Make loadOrCreate accept generate options

### PR DESCRIPTION
**Pull request by Powersource**
I'm working on https://github.com/ssbc/ssb-tribes2/issues/10 and to do that I need to adapt the tests there. And those tests create their keys with loadOrCreate.

* [x] update docs

### CODE REVIEW

**Comment by Powersource** [comment]
@staltz @mixmix

**Review by mixmix — APPROVED** [review]
From my read of this this is a non-breaking change right?

Seems good to me (reviewed on phone)

**Comment by Powersource** [comment]
Yep should be non-breaking

**Comment by Powersource** [comment]
@mixmix @staltz i can't merge, do you want to do that and publish a new version?

**Comment by staltz** [comment]
As said [on the tribes2 PR](https://github.com/ssbc/ssb-tribes2/pull/12#discussion_r995515270), I think this change is quite deep in the SSB stack and breaks a strong (legacy) assumption that classic feed format is used everywhere. E.g. there are places where we convert from a multiserver/shs address to SSB ID, by plucking the `public` base64 and adding `@` in front and `.ed25519` in the end.

So could we put this PR on hold or close it?

**Comment by Powersource** [comment]
@staltz why not give the user the option at least? And if not the feed format, this will allow the user to set the key seed too.

**Comment by staltz** [comment]
Good point

**Comment by mixmix** [comment]
If this is a non-breaking change @Powersource I recommend we merge + publish
Will make sure this is added to npm org

**Comment by Powersource** [comment]
@mixmix merged now. will you publish?

**Pull request merged**
